const shows = [
  {
    id: 1,
    title: "Alias Grace",
    year: 2017,
    genres: ["Drama", "Crime"],
    stars: ["Sarah Gadon", "Edward Holcroft"],
    creator: "Sarah Polley",
    seasons: 1,
    episodes: 6,
    isFavorite: false,
    poster: "assets/tv/alias-grace.jpeg",
    description:
      "A young Irish immigrant is convicted of murder under mysterious circumstances.",
  },
  {
    id: 2,
    title: "Breaking Bad",
    year: 2008,
    genres: ["Crime", "Drama"],
    stars: ["Bryan Cranston", "Aaron Paul"],
    creator: "Vince Gilligan",
    seasons: 5,
    episodes: 62,
    isFavorite: false,
    poster: "assets/tv/breaking-bad.jpeg",
    description:
      "A high school chemistry teacher turns to manufacturing methamphetamine.",
  },
  {
    id: 3,
    title: "Chernobyl",
    year: 2019,
    genres: ["Drama", "History"],
    stars: ["Jared Harris", "Stellan Skarsgård"],
    creator: "Craig Mazin",
    seasons: 1,
    episodes: 5,
    isFavorite: false,
    poster: "assets/tv/chernobyl.jpeg",
    description:
      "A dramatization of the 1986 nuclear disaster in the Soviet Union.",
  },
  {
    id: 4,
    title: "Friends",
    year: 1994,
    genres: ["Comedy", "Romance"],
    stars: ["Jennifer Aniston", "Courteney Cox", "Matthew Perry"],
    creator: "David Crane & Marta Kauffman",
    seasons: 10,
    episodes: 236,
    isFavorite: false,
    poster: "assets/tv/friends.jpeg",
    description: "Six friends navigate life and love in New York City.",
  },
  {
    id: 5,
    title: "Ginger & Rosa",
    year: 2012,
    genres: ["Drama"],
    stars: ["Elle Fanning", "Alice Englert"],
    creator: "Sally Potter",
    seasons: 1,
    episodes: 1,
    isFavorite: false,
    poster: "assets/tv/ginger-and-rosa.jpeg",
    description:
      "Two teenage girls face friendship and fear during the Cold War era.",
  },
  {
    id: 6,
    title: "Inventing Anna",
    year: 2022,
    genres: ["Drama", "Crime"],
    stars: ["Julia Garner", "Anna Chlumsky"],
    creator: "Shonda Rhimes",
    seasons: 1,
    episodes: 9,
    isFavorite: false,
    poster: "assets/tv/inventing-anna.jpeg",
    description:
      "The story of a fake German heiress who conned New York’s elite.",
  },
  {
    id: 7,
    title: "Jessica Jones",
    year: 2015,
    genres: ["Action", "Drama"],
    stars: ["Krysten Ritter", "David Tennant"],
    creator: "Melissa Rosenberg",
    seasons: 3,
    episodes: 39,
    isFavorite: false,
    poster: "assets/tv/jessica-jones.jpeg",
    description:
      "A private investigator with super strength faces dark personal demons.",
  },
  {
    id: 8,
    title: "New Girl",
    year: 2011,
    genres: ["Comedy", "Romance"],
    stars: ["Zooey Deschanel", "Jake Johnson"],
    creator: "Elizabeth Meriwether",
    seasons: 7,
    episodes: 146,
    isFavorite: false,
    poster: "assets/tv/new-girl.jpeg",
    description:
      "An upbeat woman moves in with three single men after a bad breakup.",
  },
  {
    id: 9,
    title: "Russian Doll",
    year: 2019,
    genres: ["Comedy", "Sci-Fi"],
    stars: ["Natasha Lyonne"],
    creator: "Natasha Lyonne",
    seasons: 2,
    episodes: 15,
    isFavorite: false,
    poster: "assets/tv/russian-doll.jpeg",
    description: "A woman relives the same night over and over in a time loop.",
  },
  {
    id: 10,
    title: "Shadow and Bone",
    year: 2021,
    genres: ["Fantasy", "Drama"],
    stars: ["Jessie Mei Li", "Ben Barnes"],
    creator: "Eric Heisserer",
    seasons: 2,
    episodes: 16,
    isFavorite: false,
    poster: "assets/tv/shadow-and-bone.jpeg",
    description:
      "A young soldier discovers a power that could unite her war-torn world.",
  },
  {
    id: 11,
    title: "The Chilling Adventures of Sabrina",
    year: 2018,
    genres: ["Fantasy", "Horror"],
    stars: ["Kiernan Shipka"],
    creator: "Roberto Aguirre-Sacasa",
    seasons: 4,
    episodes: 36,
    isFavorite: false,
    poster: "assets/tv/the-chilling-adventure-of-sabrina.jpeg",
    description: "A dark reimagining of Sabrina the Teenage Witch.",
  },
  {
    id: 12,
    title: "The Office",
    year: 2005,
    genres: ["Comedy"],
    stars: ["Steve Carell", "John Krasinski"],
    creator: "Greg Daniels",
    seasons: 9,
    episodes: 201,
    isFavorite: false,
    poster: "assets/tv/the-office.jpeg",
    description: "A mockumentary about the daily lives of office employees.",
  },
  {
    id: 13,
    title: "The Outsider",
    year: 2020,
    genres: ["Crime", "Mystery"],
    stars: ["Ben Mendelsohn"],
    creator: "Richard Price",
    seasons: 1,
    episodes: 10,
    isFavorite: false,
    poster: "assets/tv/the-outsider.jpeg",
    description:
      "A gruesome murder investigation leads to supernatural horrors.",
  },
  {
    id: 14,
    title: "The Queen’s Gambit",
    year: 2020,
    genres: ["Drama"],
    stars: ["Anya Taylor-Joy"],
    creator: "Scott Frank",
    seasons: 1,
    episodes: 7,
    isFavorite: false,
    poster: "assets/tv/the-queens-gambit.jpeg",
    description:
      "A young chess prodigy rises to fame while battling addiction.",
  },
  {
    id: 15,
    title:
      "The Woman in the House Across the Street from the Girl in the Window",
    year: 2022,
    genres: ["Comedy", "Mystery"],
    stars: ["Kristen Bell"],
    creator: "Rachel Ramras",
    seasons: 1,
    episodes: 8,
    isFavorite: false,
    poster: "assets/tv/the-woman-in-the-house.jpeg",
    description:
      "A parody mystery involving wine, casseroles, and suspicious neighbors.",
  },
  {
    id: 16,
    title: "True Detective",
    year: 2014,
    genres: ["Crime", "Drama"],
    stars: ["Matthew McConaughey", "Woody Harrelson"],
    creator: "Nic Pizzolatto",
    seasons: 4,
    episodes: 30,
    isFavorite: false,
    poster: "assets/tv/true-detective.jpeg",
    description:
      "Anthology series exploring dark crimes and the people who investigate them.",
  },
  {
    id: 17,
    title: "Wednesday",
    year: 2022,
    genres: ["Fantasy", "Mystery"],
    stars: ["Jenna Ortega"],
    creator: "Alfred Gough & Miles Millar",
    seasons: 1,
    episodes: 8,
    isFavorite: false,
    poster: "assets/tv/wednesday.jpeg",
    description:
      "Wednesday Addams navigates school, murder, and psychic mysteries.",
  },
  {
    id: 18,
    title: "You",
    year: 2018,
    genres: ["Crime", "Thriller"],
    stars: ["Penn Badgley"],
    creator: "Greg Berlanti",
    seasons: 4,
    episodes: 40,
    isFavorite: false,
    poster: "assets/tv/you.jpeg",
    description:
      "A charming man becomes dangerously obsessed with the women he loves.",
  },
];

// Load favorites from localStorage and sync with shows array
function initializeFavorites() {
  const savedIDs = JSON.parse(localStorage.getItem("shows"));

  if (savedIDs && Array.isArray(savedIDs)) {
    shows.forEach((show) => {
      show.isFavorite = savedIDs.includes(show.id);
    });
  }
};

// Call this immediately
initializeFavorites();

export { shows };
